version: '3.8'
services:
  registry:
    image: registry:2
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_HTTP_HOST: "http://registry.sillycat.com"
    volumes:
     - /opt/registry/data:/var/lib/registry
     - /opt/registry/config/config.yml:/etc/docker/registry/config.yml
    networks:
     - traefik-net
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.registry.rule: "Host(`registry.sillycat.com`)"
        traefik.http.routers.registry.middlewares: "traefik-auth"
        traefik.http.services.registry.loadbalancer.server.port: "5000"
        traefik.enable: "true"
      placement:
        constraints:
         - node.role == manager
  ui:
    image: joxit/docker-registry-ui:static
    environment:
      REGISTRY_TITLE: "Sillycat Registry"
      REGISTRY_URL: "http://registry:5000"
      NGINX_PROXY_HEADER_X_Forwarded_For: "$$proxy_add_x_forwarded_for"
      NGINX_PROXY_HEADER_Authorization: "Basic YWRtaW46MTIzNDU2"
      DELETE_IMAGES: "true"
    depends_on: registry
    volumes:
     - /opt/registry/config/nginx.env:/etc/nginx/.env 
    networks:
     - traefik-net
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.registryui.rule: "Host(`registry-ui.sillycat.com`)"
        #traefik.http.routers.registryui.middlewares: "traefik-auth"
        traefik.http.services.registryui.loadbalancer.server.port: "80"
        traefik.enable: "true"
      placement:
        constraints:
         - node.role == manager
networks:
  traefik-net:
    external: true