version: '3.8'
services:
  web:
    image: joxit/docker-registry-ui:latest
    environment:
      URL: "http://registry.sillycat.com"
      NGINX_PROXY_HEADER_X_Forwarded_For: "$$proxy_add_x_forwarded_for"
      NGINX_PROXY_HEADER_Authorization: ""
      DELETE_IMAGES: "true"
    volumes:
     - /opt/registry/config/nginx.env:/etc/nginx/.env 
    networks:
     - traefik-net
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.registry.rule: "Host(`registry-ui.sillycat.com`)"
        #traefik.http.routers.registry.middlewares: "traefik-auth"
        traefik.http.services.registry.loadbalancer.server.port: "80"
        traefik.enable: "true"
      placement:
        constraints:
         - node.role == manager
networks:
  traefik-net:
    external: true