version: '3.8'
services:
  web:
    image: joxit/docker-registry-ui:static
    environment:
      REGISTRY_URL: "http://registry.sillycat.com"
      NGINX_PROXY_HEADER_X_Forwarded_For: "$$proxy_add_x_forwarded_for"
      NGINX_PROXY_HEADER_Authorization: "Basic YWRtaW46MTIzNDU2"
      DELETE_IMAGES: "true"
    volumes:
     - /opt/registry/config/nginx.env:/etc/nginx/.env 
    networks:
     - traefik-net
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.registryui.rule: "Host(`registry-ui.sillycat.com`)"
        #traefik.http.routers.registryui.middlewares: "traefik-auth"
        traefik.http.services.registryui.loadbalancer.server.port: "80"
        traefik.enable: "true"
      placement:
        constraints:
         - node.role == manager
networks:
  traefik-net:
    external: true